USE master;
GO

IF EXISTS (SELECT * FROM sys.databases WHERE name = 'RescuePetDB')
DROP DATABASE RescuePetDB;
GO

CREATE DATABASE RescuePetDB;
GO

USE RescuePetDB;
GO

CREATE TABLE PET (
    PetID INT PRIMARY KEY IDENTITY(1,1),
    Name VARCHAR(100) NOT NULL,
    Type VARCHAR(50) NOT NULL,
    Breed VARCHAR(100),
    Location VARCHAR(100) NOT NULL,
    Age INT NOT NULL,
    Gender VARCHAR(10),
    Weight DECIMAL(5, 2), 
    Story VARCHAR(MAX) NOT NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'Available',
    PostedBy VARCHAR(100) NOT NULL,
    ImagePath VARCHAR(255)
);

CREATE TABLE ADOPTION_RECORD (
    AdoptionID INT PRIMARY KEY IDENTITY(1,1),
    PetID INT NOT NULL FOREIGN KEY REFERENCES PET(PetID),
    PetName VARCHAR(100) NOT NULL,
    UserName VARCHAR(100) NOT NULL,
    AdoptionDate DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE [USER] ( 
    UserID INT PRIMARY KEY IDENTITY(1,1),
    FullName VARCHAR(100) NOT NULL,
    PhoneNumber VARCHAR(20)
);

CREATE TABLE DONATION (
    DonationID INT PRIMARY KEY IDENTITY(1,1),
    DonorName VARCHAR(100),
	PhoneNumber VARCHAR(20),
    Amount DECIMAL(10, 2) NOT NULL,
);
GO