//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u24753328_HW02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADOPTION_RECORD
    {
        public int AdoptionID { get; set; }
        public int PetID { get; set; }
        public string PetName { get; set; }
        public string UserName { get; set; }
        public System.DateTime AdoptionDate { get; set; }
    
        public virtual PET PET { get; set; }
    }
}
