//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u24753328_HW02.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RescuePetDBEntities2 : DbContext
    {
        public RescuePetDBEntities2()
            : base("name=RescuePetDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADOPTION_RECORD> ADOPTION_RECORD { get; set; }
        public DbSet<DONATION> DONATIONs { get; set; }
        public DbSet<PET> PETs { get; set; }
        public DbSet<USER> USERs { get; set; }
    }
}
