//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u24753328_HW02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PET
    {
        public PET()
        {
            this.ADOPTION_RECORD = new HashSet<ADOPTION_RECORD>();
        }
    
        public int PetID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Breed { get; set; }
        public string Location { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Story { get; set; }
        public string Status { get; set; }
        public string PostedBy { get; set; }
        public string ImagePath { get; set; }
    
        public virtual ICollection<ADOPTION_RECORD> ADOPTION_RECORD { get; set; }
    }
}
